server:
  servlet:
    context-path: /api
  error:
    include-message: always

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/studentrecorder
    username: postgres
    password: password
    pool-size: 30